CREATE DATABASE UST;

USE UST;


CREATE TABLE EMP(EMPNO INT  NOT NULL,
        ENAME VARCHAR(10),
        JOB NVARCHAR(9),
        MGR INT,
        HIREDATE DATE,
        SAL INT,
        COMM INT,
        DEPTNO INT);

INSERT INTO EMP VALUES
        (7369, 'SMITH', 'CLERK', 7902,'17-DEC-1980',  800, NULL, 20);
INSERT INTO EMP VALUES
        (7499, 'ALLEN', 'SALESMAN', 7698, '20-FEB-1981', 1600,  300, 30);
INSERT INTO EMP VALUES
        (7521, 'WARD',  'SALESMAN', 7698, '22-FEB-1981', 1250,  500, 30);
INSERT INTO EMP VALUES
        (7566, 'JONES', 'MANAGER', 7839, '2-APR-1981',  2975, NULL, 20);
INSERT INTO EMP VALUES
        (7654, 'MARTIN', 'SALESMAN', 7698,'28-SEP-1981', 1250, 1400, 30);
INSERT INTO EMP VALUES
        (7698, 'BLAKE',  'MANAGER',  7839, '1-MAY-1981',  2850, NULL, 30);
INSERT INTO EMP VALUES
        (7782, 'CLARK',  'MANAGER',  7839, '9-JUN-1981',  2450, NULL, 10);
INSERT INTO EMP VALUES
        (7788, 'SCOTT',  'ANALYST',  7566, '09-DEC-1982', 3000, NULL, 20);
INSERT INTO EMP VALUES
        (7839, 'KING',   'PRESIDENT', NULL, '17-NOV-1981', 5000, NULL, 10);
INSERT INTO EMP VALUES
        (7844, 'TURNER', 'SALESMAN',  7698, '8-SEP-1981',  1500,    0, 30);
INSERT INTO EMP VALUES
        (7876, 'ADAMS',  'CLERK', 7788, '12-JAN-1983', 1100, NULL, 20);
INSERT INTO EMP VALUES
        (7900, 'JAMES',  'CLERK', 7698, '3-DEC-1981',   950, NULL, 30);
INSERT INTO EMP VALUES
        (7902, 'FORD',   'ANALYST', 7566, '3-DEC-1981',  3000, NULL, 20);
INSERT INTO EMP VALUES
        (7934, 'MILLER', 'CLERK', 7782, '23-JAN-1982', 1300, NULL, 10);


SELECT * FROM EMP;

SELECT ENAME, JOB, HIREDATE FROM EMP;

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" FROM EMP;

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" 
FROM EMP
WHERE JOB='CLERK'

 SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" 
FROM EMP
WHERE EMPNO=7900

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE SAL BETWEEN 1000 AND 1500

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1982-12-31'

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY",DEPTNO AS "DEPARTMENT"
FROM EMP
WHERE DEPTNO NOT IN(10,20)

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE ENAME LIKE 'J____'

SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE ENAME LIKE 'A%'
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE ENAME LIKE 'M%R'
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE ENAME NOT LIKE 'M%R'
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY"
FROM EMP
WHERE ENAME LIKE 'M%[E-R]'
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY",DEPTNO AS "DEPARTMENT"
FROM EMP
ORDER BY ENAME DESC
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY",DEPTNO AS "DEPARTMENT"
FROM EMP
ORDER BY ENAME,HIREDATE
SELECT ENAME AS "EMP NAME", JOB AS "DESIGNATION", HIREDATE AS "JOIN DATE" ,SAL AS "SALARY",DEPTNO AS "DEPARTMENT"
FROM EMP
ORDER BY HIREDATE,ENAME DESC

SELECT ENAME AS "EMP NAME",JOB AS "DESIGNATION" ,DEPTNO
FROM EMP
GROUP BY DEPTNO,ENAME,JOB
ORDER BY DEPTNO DESC

SELECT ENAME AS "EMP NAME",JOB AS "DESIGNATION" ,DEPTNO
FROM EMP
GROUP BY DEPTNO,ENAME,JOB
HAVING DEPTNO IN(20,10)
ORDER BY DEPTNO DESC


SELECT SUM(SAL) AS "TOTAL SALARY",DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO IN(10,20)

SELECT COUNT(ENAME) AS "Total Employees",DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO IN(10,30)

--join
CREATE TABLE DEPARTMENT(DEPTNO INT,DNAME NVARCHAR(5));
INSERT INTO DEPARTMENT VALUES(10,'HR')
INSERT INTO DEPARTMENT VALUES(20,'IT')
INSERT INTO DEPARTMENT VALUES(30,'Sales')
INSERT INTO DEPARTMENT VALUES(40,'NW')

SELECT * FROM DEPARTMENT


SELECT EMP.ENAME,EMP.DEPTNO,DEPARTMENT.DNAME
FROM EMP INNER JOIN DEPARTMENT
ON EMP.DEPTNO=DEPARTMENT.DEPTNO
WHERE EMP.DEPTNO IN(10,20)




